<a href="https://colab.research.google.com/github/simseoyoung/Deep-Learning/blob/main/CH.1/1_1)_Library_%26_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [1]모듈 불러오기

In [ ]:
import torch
print("Pytorch 버전: {}".format(torch.__version__))

import pandas as pd
print("pandas 버전: {}".format(pd.__version__))

import matplotlib
print("matplotlib 버전: {}".format(matplotlib.__version__))

import numpy as np
print("NumPy 버전: {}".format(np.__version__))

import sklearn
print("scikit-learn 버전: {}".format(sklearn.__version__))

Pytorch 버전: 1.5.0
pandas 버전: 1.0.1
matplotlib 버전: 3.1.3
NumPy 버전: 1.18.1
scikit-learn 버전: 0.22.1


## [2] Python 기본

In [ ]:
# print
print('Hello baro')

Hello baro


In [ ]:
# Variables
num = 3
print(num, type(num))

real_value = 1.0
print(real_value, type(real_value))

string = 'data'
print(string, type(string))

3 <class 'int'>
1.0 <class 'float'>
data <class 'str'>


In [ ]:
#자료구조, 리스트
baro_list = [1, 2, 3, 4, 5]

print(type(baro_list))
print(baro_list)

<class 'list'>
[1, 2, 3, 4, 5]


In [ ]:
#리스트에 값 추가하기
add_value=6

baro_list.append(add_value)

print(baro_list) 

[1, 2, 3, 4, 5, 6]


In [ ]:
# list 크기
len(baro_list)

6

In [ ]:
# enumerate 낱낱이 세다
baro_list = ['하나','둘', '셋','넷','다섯']

for index , value in enumerate(baro_list): # index값과 list 값을 return
    print(index, value)


0 하나
1 둘
2 셋
3 넷
4 다섯


## [3] Numpy

#### 1) array - 다차원 연산의 기본 데이터 타입

In [ ]:
# np array and print
num = np.array(3)
print("num →", num)
print(type(num))
print('\n')

string = np.array('data')
print("string →", string)
print(type(string))
print('\n')

arr_onerank = np.array([1, 2, 3])
print("arr_onerank →", arr_onerank)
print(type(arr_onerank))
print('\n')

arr_matrix = np.array([[1, 2, 3],[4, 5, 6]])
print("arr_matrix →", arr_matrix)
print(type(arr_matrix))

num → 3
<class 'numpy.ndarray'>


string → data
<class 'numpy.ndarray'>


arr_onerank → [1 2 3]
<class 'numpy.ndarray'>


arr_matrix → [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


#### 2) array size & reshape

In [ ]:
# shape, reshape
print(num.shape)
print(arr_onerank.shape)
print(arr_matrix.shape)
print(arr_matrix)

arr_reshape = arr_matrix.reshape(-1) # "-1"은 나머지 성분을 차례로 배열
print('arr_reshape의 shape: ',arr_reshape.shape)
arr_reshape

()
(3,)
(2, 3)
[[1 2 3]
 [4 5 6]]
arr_reshape의 shape:  (6,)


array([1, 2, 3, 4, 5, 6])

#### 3) array 생성

In [ ]:
np.random.seed(777)
# Generate data from numpy
linspace_arr = np.linspace(0, 10, 5)
print(f'linspace_arr : \n {linspace_arr}\n')

# 0과 1사이의 난수 생성
rand_arr = np.random.rand(10)
print(f'rand_arr : \n {rand_arr}\n')

# randn 명령은 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규 분포를 따르는 난수를 생성한다. 인수 사용법은 rand 명령과 같다.
normal_arr = np.random.randn(1,2)
print(f'normal_arr : \n {normal_arr}')



linspace_arr : 
 [ 0.   2.5  5.   7.5 10. ]

rand_arr : 
 [0.15266373 0.30235661 0.06203641 0.45986034 0.83525338 0.92699705
 0.72698898 0.76849622 0.26920507 0.64402929]

normal_arr : 
 [[-1.75244452  1.00244907]]


In [ ]:
# Arange 함수 - 범위내 지정된 간격으로 array 생성
arange_arr= np.arange(1, 10, 2)# (stop) or (start,stop) or (start, stop, step) # stop은 포함되지않음
arange_arr

array([1, 3, 5, 7, 9])

In [ ]:
arange_arr2= np.arange(0, 5, 1)
arange_arr2

array([0, 1, 2, 3, 4])

#### 4) numpy 합치기

In [ ]:
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1, arr2], axis=0 )

print(arr3)

[1 2 3 4 5 6]


In [ ]:

arr1 = np.arange(3).reshape(1, 3)
arr2 = np.arange(6).reshape(2, 3)
arr_concat = np.concatenate([arr1, arr2], axis=0)

print(arr1,'\n')
print(arr2,'\n')
print(arr_concat.shape,'\n')
print(arr_concat)


[[0 1 2]] 

[[0 1 2]
 [3 4 5]] 

(3, 3) 

[[0 1 2]
 [0 1 2]
 [3 4 5]]


## [4] Pandas

In [ ]:
#csv파일 읽기(Comma-separated variables)
df_raw = pd.read_csv("./BostonHousing.csv") 

In [ ]:
print(df_raw.shape)
df_raw

(506, 14)


crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [ ]:
# Column 삭제하기
# drop으로 컬럼을 제거할때 axis=1을 기입 (axis =0 은 row 를 제거)

print("crim 컬럼 삭제")

df_raw_new = df_raw.drop('crim', axis=1 )
df_raw_new.head()

crim 컬럼 삭제


zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio   black  \
0  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   
1   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   
2   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   
3   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   
4   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   

   lstat  medv  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
3   2.94  33.4  
4   5.33  36.2

## [5] Tensor

#### 1) Tensor 생성

In [ ]:
#Tensor 생성
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.]) # real value 
print(t)
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [ ]:
torch.manual_seed(777) #동일한 랜덤 값을 사용할 수 있도록 해준다

x = torch.rand(2, 3) #0~1사이의 숫자를 랜덤으로 반환
print(x)

x = torch.randint(10, size=(2,3)) #지정 범위내 숫자를 랜덤으로 반환
print(x)

x = torch.randn(2,3) # Z(0,1)인 가우시안 분포를 따르는 수를 랜덤 반환 
x

tensor([[0.0819, 0.4911, 0.4033],
        [0.3859, 0.8813, 0.8811]])
tensor([[7, 7, 3],
        [4, 1, 7]])


tensor([[ 1.4425, -1.4711, -1.3173],
        [ 2.3271,  0.0894,  0.6558]])

In [ ]:
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# torch.ones(2,3) -> [[0,0,0],[0,0,0]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0, 3, 0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [ ]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### 2) List, Numpy --> Tensor로 변환

In [ ]:
# list 로부터 2x3 텐서 생성
x_list = [[1, 2, 3], [4, 5, 6]]
x = torch.Tensor(x_list)
print(x)

# numpy array 로부터 2x3 텐서 생성
x_numpy = np.array([[1, 2, 3], [4, 5, 6]])
x = torch.Tensor(x_numpy)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### 3) Tensor 크기 변경하기

In [ ]:
#view, reshape 함수
x = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])

x = torch.FloatTensor(x)

In [ ]:
print(x.shape)

tensor_x = x.view(-1, 3)
print(tensor_x.shape)

tensor_x = x.reshape(-1,2)
print(tensor_x.shape)


torch.Size([2, 2, 3])
torch.Size([4, 3])
torch.Size([6, 2])


#### 4) Tensor 차원 추가 및 삭제

In [ ]:
# Squeeze 함수
x1 = torch.FloatTensor(10, 1, 3, 1, 4) # rank를 줄여주는 기능

x2 = x1.squeeze()

print(x1.size())
print(x2.size())

torch.Size([10, 1, 3, 1, 4])
torch.Size([10, 3, 4])


In [ ]:
# Unsqueeze 함수
x1 = torch.FloatTensor(10,3,4) #rank를 늘려주는 기능

x2 = torch.unsqueeze(x1, dim=1)

print(x1.size())
print(x2.size())

torch.Size([10, 3, 4])
torch.Size([10, 1, 3, 4])


#### 5) Tensor 합치기

In [ ]:
torch.manual_seed(777)
x = torch.randint(10, size=(2, 3))
y = torch.randint(10, size=(2, 3))

z = torch.cat([x,y], dim=0 )

print(x)
print(y)
print(z.shape)
print(z)

tensor([[5, 9, 1],
        [8, 5, 7]])
tensor([[7, 7, 3],
        [4, 1, 7]])
torch.Size([4, 3])
tensor([[5, 9, 1],
        [8, 5, 7],
        [7, 7, 3],
        [4, 1, 7]])


#### 6) 평균, 분산 구하기

In [ ]:
x = torch.FloatTensor([1, 100])

print(x)
print(x.mean())
print(x.var())

tensor([  1., 100.])
tensor(50.5000)
tensor(4900.5000)


#### 7) Tensor 인덱싱

In [ ]:
z

tensor([[5, 9, 1],
        [8, 5, 7],
        [7, 7, 3],
        [4, 1, 7]])

In [ ]:
z[3]

tensor([4, 1, 7])

In [ ]:
z[0,1]

tensor(9)

In [ ]:
z[:,1]

tensor([9, 5, 7, 1])

In [ ]:
z[-1]

tensor([4, 1, 7])

####  Q1) z[:  ,  :-1] =?

In [ ]:
z[:,:-1]

tensor([[5, 9],
        [8, 5],
        [7, 7],
        [4, 1]])

#### Q2)  ? = [[7,7,3],  [4,1,7]] 

In [ ]:
z[2:, :]

tensor([[7, 7, 3],
        [4, 1, 7]])

-------------------------------------------------------------------

In [ ]:
torch.manual_seed(777)
x = torch.randint(10, size=(2, 3, 4))
x

tensor([[[5, 9, 1, 8],
         [5, 7, 7, 7],
         [3, 4, 1, 7]],

        [[2, 0, 6, 3],
         [2, 3, 0, 0],
         [9, 5, 4, 2]]])

#### Q1) x[:,2,:] = ?

In [ ]:
x[:, 2, :]

tensor([[3, 4, 1, 7],
        [9, 5, 4, 2]])

#### Q2) ? = [[5, 9, 1],  [2, 0, 6]]

In [ ]:
x[:, 0, :3 ]

tensor([[5, 9, 1],
        [2, 0, 6]])